<HTML>
<HEAD>
<TITLE>PROGRAMA 1</TITLE>
</HEAD>
<BODY BGCOLOR= OLIVE>
<SCRIPT>
var nom;
nom=prompt("ESCRIBA SU NOMBRE COMPLETO", "NOMBRE");
alert("\nBIENVENID@:" + "\n" + nom);
var ed;
ed=prompt("ESCRIBA SU EDAD", "EDAD");
var fch;
fch=prompt("ESCRIBA SU FECHA DE NACIMIENTO", "DD/MM/AAAA");
var tlf;
tlf=prompt("NUMERO TELEFONICO", "10 DIGITOS");
var sex;
sex=prompt("SEXO", "FEMENINO O MASCULINO");
alert("TUS DATOS SON CORRECTOS:"+"\nNOMBRE:"+nom+"\nEDAD:"+ed+" \nFECHA DE NACIMIENTO:"+fch+"\nNUMERO TELEFONICO:"+tlf+"\nSEXO:"+sex+ "\nDA CLIC EN ACEPTAR");
var dato1;
dato1=prompt("INGRESA UN NUMERO", "ejmp:10");
var dato2;
dato2=prompt("INGRESA UN NUMERO", "ejmp:5");
var divicion=dato1/dato2;
alert("EL RESULTADO DE LA DIVICION ES =" + "\n"+ divicion);                      
</SCRIPT>
<FONT COLOR=BLACK SIZE=70 FACE=ALGERIAN>
<MARQUEE DIRECTION=LEFT BGCOLOR=WHITE BEHAIVOR=ALTERNATE SCROLLAMOUN=100 LOOP=50>
HORARIO
</MARQUEE> </FONT>
<FONT COLOR=BLACK SIZE=70 FACE=ALGERIAN>
<MARQUEE DIRECTION=RIGHT BGCOLOR=BROWN BEHAIVOR=ALTERNATE SCROLLAMOUN=70 LOOP=73>
JATXELL
</MARQUEE> </FONT>
<FONT COLOR=BLACK SIZE=70 FACE=ALGERIAN>
<MARQUEE DIRECTION=DOWN BGCOLOR=YELLOW BEHAIVOR=ALTERNATE SCROLLAMOUN=130 LOOP=100>
TERCERO 1
</MARQUEE> </FONT>
<IMG SRC=E:\IMAGENES\1.JFIF>
</IMG>
<IMG SRC=E:\IMAGENES\2.JFIF>
</IMG>
<IMG SRC=E:\IMAGENES\3.JFIF>
</IMG>
<IMG SRC=E:\IMAGENES\4.PNG>
</IMG>
<IMG SRC=E:\IMAGENES\5.JFIF>
</IMG>
<CENTER>
<VIDEO SRC=E:\VIDEOS\MMX.MP4 CONTROLS>
</VIDEO>
<VIDEO SRC=E:\VIDEOS\GERARDO ORTIZ.MP4 CONTROLS>
</VIDEO>
<H2> HORARIO </H2>
<TABLE BORDER="2" WIDTH="100%">
<THEAD BGCOLOR=YELLOW>
<TR>
<TH>LUNES</TH>
<TH>MARTES</TH>
<TH>MIERCOLES</TH>
<TH>JUEVES</TH>
<TH>VIERNES</TH>
</TR>
<TR>
</THEAD>
<TBODY ALIGN="CENTER" BGCOLOR=WHITE>
<TR>
<TD>PROGRAMACION</TD>
<TD>ECONOMIA</TD>
<TD>DERECHO</TD>
<TD>INGLES</TD>
<TD>PSICOLOGIA </TD>
<TR>
<TR>
<TD>PROGRAMACION </TD>
<TD>GEOGRAFIA</TD>
<TD>DERECHO </TD>
<TD>INGLES </TD>
<TD>ECONOMIA </TD>
<TR>
<TR>
<TD>PSICOLOGIA</TD>
<TD>GEOGRAFIA</TD>
<TD>MATEMATICAS </TD>
<TD>POGRAMACION </TD>
<TD>MATEMATICAS </TD>
<TR>
<TR>
<TD>PSICOLOGIA</TD>
<TD>GEOGRAFIA</TD>
<TD>MATEMATICAS </TD>
<TD>POGRAMACION </TD>
<TD>MATEMATICAS </TD>
<TR>
</TBODY>
<AUDIO SRC=E:\AUDIO\AC.MP3 CONTROLS>
</AUDIO>
<LI>TAREAS CHECK </LI>
<LI>SI</LI>
<LI>NO</LI>
<B>HORARIO</B><I>DE</I><V>CLASES</V><S> 8:00-11:20</S>
<A HREF=E:\PROG\PROG25.HTML>
PROGRAMA 25</A>
<A HREF=E:\PROG\PROG3.HTML>
PROGRAMA 3</A>
</TABLE>
</BODY>
</HTML>
</A>
